var nome = "Thomas Erick";
var n1 = 30;
var n2 = 20;
var frase = "Japão é o maior país do mundo";
//alert(nome + "tem: " + n1 + " anos");
//alert(n1 + n2);
console.log(nome);
console.log(n1 + n2);
console.log(frase.toUpperCase());
console.log(frase.toLowerCase());
console.log(frase.replace("Japão", "Brasil"));
